services:
  - type: web
    name: fake-user-generator
    env: python
    buildCommand: cd task6 && pip install -r requirements.txt
    startCommand: cd task6 && gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fake-user-db
          property: connectionString
    plan: free

databases:
  - name: fake-user-db
    plan: free
