services:
  - type: web
    name: fake-user-generator
    runtime: python
    repo: https://github.com/Khalodddd/data_engineering_tasks
    branch: main
    rootDir: task6
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fake-user-db
          property: connectionString
    plan: free
    autoDeploy: true

databases:
  - name: fake-user-db
    plan: free
    databaseName: fake_user_data
    user: fake_user
